# Generated by Django 4.2.9 on 2024-08-09 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Entertaining', 'Entertaining'), ('Motivational', 'Motivational'), ('Emotional', 'Emotional'), ('Sadness', 'Sadness'), ('Thought-Provoking', 'Thought-Provoking'), ('Romantic', 'Romantic')], max_length=50)),
                ('hashtag', models.CharField(max_length=150)),
                ('contect', models.CharField(max_length=500)),
                ('post_image', models.FileField(upload_to='static/Posts/')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('post_update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
