# Generated by Django 4.2.9 on 2024-08-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
    ]
