# Generated by Django 4.2.9 on 2024-08-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='static/Profile/'),
        ),
    ]
