# Generated by Django 4.2.9 on 2024-08-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='follow_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
